name: decision-transformer
dependencies:
- conda-forge::cudatoolkit=11.3.1
- python=3.9.7
- pytorch::pytorch=1.10.2=py3.9_cuda11.3_cudnn8.2.0_0
- scipy=1.7.3
- pytorch::torchvision=0.11.3=py39_cu113
- anaconda
- numpy
- pip
- pip:
  - gym==0.18.3
  - mujoco-py
  - transformers==4.5.1
  - wandb
  - matplotlib
